### ISSUE TITLE
variant identification step with  --pv_fixmod  parameters 

### ISSUE THREAD

**Issue by jiwonhong95** [bzhanglab/neoflow#5]
Hi, thank you for a great tool!
I trying out neoflow and managed to get the example file running with the help of the readme file.
However, while trying to optimize it with our data, I was unable to find descriptions of --pv_fixmod  parameters other than the fact that the format is entered in numbers (1,2,3)

Where would I be able to find which modification corresponds to which number for this parameter?
![image](https://user-images.githubusercontent.com/43137644/178171364-b4bf7434-76fe-4271-9f0f-8cc36d04c655.png)

Thank you in advance

**Comment by wenbostar** [comment]
Please find the list of modifications supported at [modification list](http://pepquery.org/data/modification/1.6.2/modification_list.txt).

**Comment by jiwonhong95** [comment]
Thank you!
